s#http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/plannet-TViaIntermediary-extension#http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/plannet-ViaIntermediary-extension#g
s#extension:tviaintermediary#extension:viaintermediary#g 
s#\"tviaintermediary\"#\"viaintermediary\"#g 
s#http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/plannet-Practitioner-Qualification-VHDIR-extension#http://hl7.org/fhir/uv/vhdir/StructureDefinition/practitioner-qualification#g  
s#extension:practitioner-qualification-vhdir#extension:practitionerqualification#g 
s#\"practitioner-qualification-vhdir\"#\"practitionerqualification\"#g 
s#http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/plannet-AvailableTime-extension#http://hl7.org/fhir/uv/vhdir/StructureDefinition/contactpoint-availabletime#g
s#extension:availabletime#extension:contactpointavailabletime#g 
s#\"availabletime\"#\"contactpointavailabletime\"#g 
s#http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/plannet-CAvailableTime-extension#http://hl7.org/fhir/uv/vhdir/StructureDefinition/contactpoint-availabletime#g
s#extension:cavailabletime#extension:contactpointavailabletime#g 
s#\"cavailabletime\"#\"contactpointavailabletime\"#g 
s#http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/plannet-TAvailableTime-extension#http://hl7.org/fhir/uv/vhdir/StructureDefinition/contactpoint-availabletime#g
s#extension:tavailabletime#extension:contactpointavailabletime#g 
s#\"tavailabletime\"#\"contactpointavailabletime\"#g 
s#http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/plannet-NAvailableTime-extension#http://hl7.org/fhir/uv/vhdir/StructureDefinition/contactpoint-availabletime#g
s#extension:navailabletime#extension:availabletime#g 
s#extension:navailabletime#extension:contactpointavailabletime#g 
s#\"navailabletime\"#\"contactpointavailabletime\"#g 
s#http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/plannet-GeoLocation-extension#http://hl7.org/fhir/StructureDefinition/geolocation#g
s#http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/plannet-IdentifierStatus-extension#http://hl7.org/fhir/uv/vhdir/StructureDefinition/identifier-status#g
s#http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/plannet-Communication-Proficiency-extension#http://hl7.org/fhir/uv/vhdir/StructureDefinition/communication-proficiency#g
s#extension:proficiency#extension:communicationproficiency#g 
s#http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/plannet-Qualification-extension#http://hl7.org/fhir/uv/vhdir/StructureDefinition/practitioner-qualification#g  
s#extension:qualification#extension:practitioner-qualification#g 

